name: New_Year_Nekeath_App_2025
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  permission_handler: ^10.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  provider: ^6.0.5
  flutter_compass: ^0.8.1
  flutter_map: ^7.0.2
  flutter_local_notifications: ^12.0.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1 # Use the latest version
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  web: true
  windows: true
  macos: true
  image_path: "assets/images/logo1.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/events.json
